blank_issues_enabled: true
contact_links:
  - name: Arank Support
    url: https://t.me/Mr_Mrs_Krishna
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://t.me/Carding_Chronicle
    about: Join this.